services:
    app:
        build:
            context: ./
            dockerfile: .docker/8.2/Dockerfile
        command: 'php artisan serve --host 0.0.0.0 --port 8000'
        ports:
            - '80:8000'
        volumes:
            - '.:/var/www/html'
        networks:
            - backend
    worker:
        build:
            context: ./
            dockerfile: .docker/8.2/Dockerfile
        command: 'php artisan queue:listen --tries=3 --backoff=3 --sleep=4'
        volumes:
            - '.:/var/www/html'
        networks:
            - backend
    db:
      image: 'mysql'
      ports:
          - '3306:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
          - backend
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    redis:
        image: redis:latest
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5
        command: ["redis-server"]
        networks:
            - backend
networks:
    backend:
        driver: bridge
